version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - ten-thousand-hours-net

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - ten-thousand-hours-net

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static
    networks:
      - ten-thousand-hours-net

volumes:
  postgres-data:
  static-data:

networks:
  ten-thousand-hours-net:
    driver: bridge