# Generated by Django 3.2.25 on 2025-06-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timer',
            name='type',
            field=models.ManyToManyField(to='core.Type'),
        ),
    ]
