# Generated by Django 3.2.25 on 2025-06-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250608_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TimerType',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='type',
        ),
        migrations.AddField(
            model_name='timer',
            name='timer_type',
            field=models.ManyToManyField(to='core.TimerType'),
        ),
    ]
