# Generated by Django 3.2.25 on 2025-06-30 18:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250608_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.timer_image_file_path),
        ),
    ]
