# Generated by Django 3.2.25 on 2025-07-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
