# Generated by Django 3.2.25 on 2025-07-15 21:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_timer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.timer_image_file_path),
        ),
    ]
